apiVersion: v1
kind: Namespace
metadata:
  name: gfdhdfghdf-prod
  labels:
    environment-id: env_cf48dc65-8eb1-403a-8b7d-6d0ef0c2a646
    project-id: project_47e848d2-cd68-4efe-82b3-38462bd7fec2
    project-name: 'gfdhdfghdf '
    environment-name: prod
    organization-id: org_b90db410-70ec-4efc-955f-90fee843d8f8
