apiVersion: v1
kind: Namespace
metadata:
  name: gfdhdfghdf-dev
  labels:
    environment-id: env_4c977613-f2d0-453f-9ead-e40dcb5368b8
    project-id: project_47e848d2-cd68-4efe-82b3-38462bd7fec2
    project-name: 'gfdhdfghdf '
    environment-name: dev
    organization-id: org_b90db410-70ec-4efc-955f-90fee843d8f8
